# データ抽出

In [13]:
import pandas as pd
import csv

In [14]:
df = pd.read_csv(f'../csv/searchResults.csv', names=['dep', 'destination', 'date', 'via', 'time', 'price'])
df = df.drop_duplicates(['destination', 'date'])
df = df.dropna()

In [30]:
df['price'] = df['price'].str.replace('JP¥|,', '', regex=True).astype(int)

In [35]:
display(df[(df['dep'] == 'SYD') & (df['price'] <= 250000)].sort_values(by='price'))

      dep    destination             date       via           time   price
93    SYD          Tokyo         6–12 Jun  Non-stop   9 hrs 45 min  119178
1450  SYD          Tokyo        22–28 Aug  Non-stop   9 hrs 45 min  119461
1916  SYD          Tokyo        24–30 Oct  Non-stop   9 hrs 45 min  129471
1227  SYD          Tokyo        18–24 Jul  Non-stop   9 hrs 45 min  131119
92    SYD  San Francisco        22–28 Aug    1 stop   22 hrs 5 min  171028
101   SYD        Seattle        17–23 Oct    1 stop  34 hrs 40 min  171028
1678  SYD    Los Angeles        5–11 Sept    1 stop  23 hrs 55 min  171434
1911  SYD    Los Angeles        24–30 Oct    1 stop  23 hrs 55 min  171434
1691  SYD        Seattle       14–21 Sept   2 stops   27 hrs 9 min  172306
91    SYD      Vancouver   31 Oct – 9 Nov    1 stop  20 hrs 20 min  172393
1458  SYD        Seattle  25 Aug – 3 Sept   2 stops   27 hrs 9 min  178976
1234  SYD        Seattle        13–22 Jul    1 stop  34 hrs 30 min  179037
1681  SYD      Vancouver        9–15 Sept    1 stop         20 hrs  180405
1012  SYD        Seattle   30 Jun – 9 Jul    1 stop  43 hrs 35 min  181520
785   SYD  San Francisco   25 May – 3 Jun   2 stops  21 hrs 45 min  189174
1225  SYD      Vancouver        13–22 Jul    1 stop         20 hrs  190542
784   SYD      Vancouver        16–24 May    1 stop  34 hrs 55 min  198145
95    SYD      Las Vegas       12–18 Sept   2 stops   29 hrs 9 min  200214
331   SYD      Las Vegas  31 Aug – 6 Sept   2 stops   29 hrs 9 min  200689
999   SYD    Los Angeles        16–24 Jun    1 stop         24 hrs  205859
1229  SYD      Las Vegas        13–22 Jul   2 stops  28 hrs 50 min  206488
113   SYD      San Diego  29 Aug – 4 Sept   2 stops   29 hrs 9 min  207799
1918  SYD      Las Vegas   26 Oct – 4 Nov   2 stops   29 hrs 9 min  208292
97    SYD       New York        17–23 Oct    1 stop  40 hrs 10 min  211480
116   SYD        Chicago        17–23 Oct    1 stop  26 hrs 55 min  211480
1687  SYD       New York       13–19 Sept    1 stop  37 hrs 20 min  211982
1226  SYD  San Francisco        22–28 Jul   2 stops   25 hrs 3 min  213584
1003  SYD  San Francisco        17–26 Jun   2 stops  21 hrs 45 min  214516
1703  SYD      San Diego         1–9 Sept   2 stops   29 hrs 9 min  218429
782   SYD      Hong Kong   30 May – 5 Jun    1 stop  27 hrs 50 min  222453
574   SYD          Paris        20–27 Jun   2 stops  37 hrs 20 min  224015
1222  SYD    Los Angeles        18–24 Jul    1 stop  24 hrs 20 min  224653
89    SYD      Hong Kong  29 Aug – 4 Sept    1 stop  17 hrs 35 min  224981
111   SYD         Prague        18–26 May   2 stops  34 hrs 20 min  225021
1000  SYD      Hong Kong         3–11 Jun    1 stop  17 hrs 35 min  225515
325   SYD      Hong Kong   25 Jul – 1 Aug    1 stop  17 hrs 35 min  225515
1912  SYD      Hong Kong   31 Oct – 6 Nov    1 stop  18 hrs 10 min  225515
1679  SYD      Hong Kong         1–8 Sept    1 stop  17 hrs 35 min  225515
1015  SYD           Rome        10–16 Jun   2 stops  34 hrs 35 min  226072
795   SYD          Paris        25–31 May   2 stops  28 hrs 15 min  229083
335   SYD        Bangkok        17–23 Jun    1 stop  19 hrs 45 min  233016
1456  SYD        Bangkok  24 Aug – 2 Sept    1 stop  19 hrs 45 min  233016
1023  SYD     Copenhagen        10–16 Jun   2 stops  33 hrs 10 min  233888
1005  SYD      Amsterdam         3–11 Jun   2 stops  33 hrs 20 min  240619
1448  SYD      Vancouver        22–30 Aug    1 stop         20 hrs  243761
1024  SYD      San Diego        13–22 Jun   2 stops   29 hrs 2 min  243772
99    SYD        Bangkok   29 Jul – 4 Aug    1 stop  19 hrs 45 min  244094
1022  SYD         Prague        17–26 Jun   2 stops  34 hrs 20 min  246103
90    SYD         London        17–26 Jun   2 stops  43 hrs 20 min  247138
790   SYD       New York   23 May – 1 Jun    1 stop   25 hrs 5 min  247461
1454  SYD       New York  29 Aug – 4 Sept   2 stops  31 hrs 19 min  248333

In [32]:
for dest in df['destination'].unique():
    display(df[(df['destination'] == dest) & (df['price'] <= 300000)].sort_values(by='price'))

      dep destination             date       via           time   price
186   HND   Singapore        16–22 May  Non-stop          7 hrs  117600
1540  HND   Singapore        5–11 Sept  Non-stop          7 hrs  117600
1775  HND   Singapore          3–9 Oct  Non-stop          7 hrs  117600
1313  HND   Singapore        15–21 Aug  Non-stop          7 hrs  117600
908   NRT   Singapore         6–12 Jun  Non-stop   7 hrs 20 min  117660
1350  NRT   Singapore          1–7 Aug  Non-stop   7 hrs 20 min  117660
121   GMP   Singapore   27 Jun – 3 Jul    1 stop  11 hrs 45 min  162124
1944  GMP   Singapore        10–16 Oct    1 stop  11 hrs 45 min  162340
814   GMP   Singapore        16–23 May    1 stop  11 hrs 45 min  162340
1478  GMP   Singapore  23 Aug – 1 Sept    1 stop         24 hrs  162340
1032  GMP   Singapore         7–16 Jun    1 stop  11 hrs 45 min  162340
1711  GMP   Singapore         1–9 Sept    1 stop   18 hrs 5 min  163888
1254  GMP   Singapore          1–8 Jul    1 stop   18 hrs 5 min  163888
0     HKG   Singapore        20–29 Jun    1 stop  15 hrs 55 min  199044
259   HKG   Singapore         4–10 Jul    1 stop  15 hrs 55 min  199305
1613  HKG   Singapore  26 Sept – 2 Oct    1 stop  15 hrs 55 min  199305
23    HKG   Singapore         2–11 Nov    1 stop  16 hrs 40 min  204529
942   HKG   Singapore   27 Jun – 6 Jul    1 stop  15 hrs 55 min  220883
1161  HKG   Singapore        15–24 Jul    1 stop  15 hrs 55 min  237557

      dep destination             date       via           time   price
131   GMP      Sydney        22–28 Aug    1 stop  24 hrs 45 min  100762
824   GMP      Sydney        16–23 May    1 stop  19 hrs 45 min  100896
1042  GMP      Sydney         7–14 Jun    1 stop  19 hrs 45 min  100896
1721  GMP      Sydney         1–7 Sept    1 stop  24 hrs 45 min  100896
1954  GMP      Sydney   31 Oct – 6 Nov    1 stop  22 hrs 25 min  100896
191   HND      Sydney        16–22 May  Non-stop   9 hrs 40 min  129170
876   HND      Sydney         6–12 Jun  Non-stop   9 hrs 40 min  129170
1318  HND      Sydney          1–7 Aug  Non-stop   9 hrs 40 min  129170
1545  HND      Sydney        5–11 Sept  Non-stop   9 hrs 40 min  129170
1780  HND      Sydney        24–30 Oct  Non-stop   9 hrs 40 min  129170
169   KUL      Sydney  29 Sept – 8 Oct    1 stop         27 hrs  246737
1     HKG      Sydney         4–10 Jul    1 stop  16 hrs 40 min  248922
730   HKG      Sydney   30 May – 5 Jun    1 stop  16 hrs 40 min  249248
943   HKG      Sydney        13–19 Jun    1 stop  16 hrs 40 min  249248
1386  HKG      Sydney        24–31 Aug    1 stop  16 hrs 40 min  249248

      dep destination             date       via           time   price
117   GMP       Tokyo        20–26 Jun  Non-stop   2 hrs 10 min   51849
1250  GMP       Tokyo          1–7 Jul  Non-stop   2 hrs 10 min   51917
1707  GMP       Tokyo       19–25 Sept  Non-stop   2 hrs 10 min   51917
810   GMP       Tokyo        16–22 May  Non-stop   2 hrs 10 min   51917
168   KUL       Tokyo  26 Sept – 3 Oct  Non-stop          7 hrs   86110
1524  KUL       Tokyo        23–29 Aug  Non-stop          7 hrs   86224
1297  KUL       Tokyo        19–25 Jul  Non-stop          7 hrs   86224
1075  KUL       Tokyo         7–13 Jun  Non-stop          7 hrs   86224
1990  KUL       Tokyo        10–17 Oct  Non-stop          7 hrs   86224
2     HKG       Tokyo        23–29 May  Non-stop   4 hrs 15 min   88708
1850  HKG       Tokyo        10–16 Oct  Non-stop   4 hrs 15 min   88824
1615  HKG       Tokyo        5–11 Sept  Non-stop   4 hrs 15 min   88824
1163  HKG       Tokyo         4–10 Jul  Non-stop   4 hrs 15 min   88824
1387  HKG       Tokyo  29 Aug – 4 Sept  Non-stop   4 hrs 15 min   88824
858   KUL       Tokyo   30 May – 5 Jun  Non-stop   7 hrs 10 min   89522
1510  SIN       Tokyo         8–14 Aug  Non-stop   7 hrs 15 min  100586
93    SYD       Tokyo         6–12 Jun  Non-stop   9 hrs 45 min  119178
1450  SYD       Tokyo        22–28 Aug  Non-stop   9 hrs 45 min  119461
69    CGK       Tokyo         9–15 May  Non-stop   7 hrs 25 min  122779
1892  CGK       Tokyo          3–9 Oct  Non-stop   7 hrs 25 min  122942
1428  CGK       Tokyo          1–7 Aug  Non-stop   7 hrs 25 min  122942
1916  SYD       Tokyo        24–30 Oct  Non-stop   9 hrs 45 min  129471
1227  SYD       Tokyo        18–24 Jul  Non-stop   9 hrs 45 min  131119
517   TPE       Tokyo        24–30 May    1 stop  10 hrs 35 min  211531
46    TPE       Tokyo        19–26 May    1 stop   5 hrs 35 min  226195
1404  TPE       Tokyo         4–12 Aug    1 stop   5 hrs 35 min  226495
1633  TPE       Tokyo         1–7 Sept    1 stop   5 hrs 35 min  226495
960   TPE       Tokyo          2–8 Jun    1 stop   5 hrs 35 min  226495
1180  TPE       Tokyo         5–11 Jul    1 stop  10 hrs 40 min  227240
281   TPE       Tokyo        11–17 Jul    1 stop   7 hrs 55 min  227240
1869  TPE       Tokyo        17–23 Oct    1 stop   5 hrs 45 min  227483

      dep destination             date       via           time   price
91    SYD   Vancouver   31 Oct – 9 Nov    1 stop  20 hrs 20 min  172393
1681  SYD   Vancouver        9–15 Sept    1 stop         20 hrs  180405
1225  SYD   Vancouver        13–22 Jul    1 stop         20 hrs  190542
157   SIN   Vancouver        10–17 Oct    1 stop  18 hrs 45 min  193494
1747  SIN   Vancouver  22 Sept – 1 Oct    1 stop  23 hrs 35 min  195245
784   SYD   Vancouver        16–24 May    1 stop  34 hrs 55 min  198145
850   SIN   Vancouver        13–19 May    1 stop  31 hrs 40 min  203307
1513  SIN   Vancouver  25 Aug – 3 Sept    1 stop  23 hrs 35 min  207735
1288  SIN   Vancouver        13–20 Jul    1 stop  23 hrs 35 min  217953
200   HND   Vancouver          3–9 Oct  Non-stop   8 hrs 55 min  232820
1554  HND   Vancouver       19–25 Sept  Non-stop   8 hrs 55 min  232820
1104  HND   Vancouver         1–10 Jul  Non-stop   8 hrs 55 min  240820
1587  NRT   Vancouver       12–18 Sept    1 stop  15 hrs 18 min  242060
1822  NRT   Vancouver   31 Oct – 7 Nov    1 stop  17 hrs 47 min  242060
233   NRT   Vancouver        17–23 Oct    1 stop  15 hrs 18 min  242060
1448  SYD   Vancouver        22–30 Aug    1 stop         20 hrs  243761
1327  HND   Vancouver  26 Aug – 1 Sept    1 stop  14 hrs 38 min  245760
885   HND   Vancouver        17–24 Jun  Non-stop   8 hrs 55 min  248820
672   HND   Vancouver   31 May – 6 Jun  Non-stop   8 hrs 55 min  248820
1136  NRT   Vancouver         8–16 Jul    1 stop  15 hrs 18 min  250060
1002  SYD   Vancouver        16–22 Jun    1 stop  34 hrs 55 min  251364
3     HKG   Vancouver   31 Oct – 6 Nov    1 stop  15 hrs 25 min  252311
1067  SIN   Vancouver   29 Jun – 7 Jul    1 stop  23 hrs 35 min  257125
732   HKG   Vancouver        20–27 May    1 stop   15 hrs 5 min  267943
1164  HKG   Vancouver         4–11 Jul    1 stop   15 hrs 5 min  271278
917   NRT   Vancouver        21–27 Jun    1 stop  15 hrs 18 min  288560
1388  HKG   Vancouver          2–8 Aug    1 stop   15 hrs 5 min  292071

      dep destination             date       via           time   price
1815  NRT     Bangkok          3–9 Oct  Non-stop   6 hrs 45 min  113720
226   NRT     Bangkok   30 May – 5 Jun  Non-stop   6 hrs 45 min  113720
1353  NRT     Bangkok        15–21 Aug  Non-stop   6 hrs 45 min  113720
698   NRT     Bangkok        23–31 May  Non-stop   6 hrs 45 min  113720
911   NRT     Bangkok         6–12 Jun  Non-stop   6 hrs 45 min  113720
1130  NRT     Bangkok        18–24 Jul  Non-stop   6 hrs 45 min  113720
190   HND     Bangkok        17–23 May  Non-stop   6 hrs 30 min  120160
1317  HND     Bangkok        22–28 Aug  Non-stop   6 hrs 30 min  120160
1094  HND     Bangkok         4–10 Jul  Non-stop   6 hrs 30 min  120160
136   GMP     Bangkok        17–23 Oct    1 stop  10 hrs 40 min  159675
1047  GMP     Bangkok   27 Jun – 3 Jul    1 stop  10 hrs 40 min  159887
1493  GMP     Bangkok  30 Aug – 5 Sept    1 stop  22 hrs 55 min  159887
829   GMP     Bangkok        16–24 May    1 stop  10 hrs 40 min  159887
4     HKG     Bangkok        5–11 Sept    1 stop  15 hrs 25 min  195792
27    HKG     Bangkok        13–19 Jun    1 stop  15 hrs 25 min  195792
1165  HKG     Bangkok         7–16 Jul    1 stop  14 hrs 50 min  201894
733   HKG     Bangkok        23–29 May    1 stop  14 hrs 50 min  201894
1852  HKG     Bangkok        12–21 Oct    1 stop  14 hrs 50 min  201894
335   SYD     Bangkok        17–23 Jun    1 stop  19 hrs 45 min  233016
1456  SYD     Bangkok  24 Aug – 2 Sept    1 stop  19 hrs 45 min  233016
1389  HKG     Bangkok         8–14 Aug    1 stop  15 hrs 25 min  240774
99    SYD     Bangkok   29 Jul – 4 Aug    1 stop  19 hrs 45 min  244094
1922  SYD     Bangkok        20–29 Oct    1 stop  19 hrs 45 min  254811

      dep destination             date       via           time   price
119   GMP      London        19–27 Oct    1 stop  35 hrs 40 min  186751
1942  GMP      London   31 Oct – 8 Nov    1 stop  36 hrs 20 min  201125
1030  GMP      London   24 Jun – 1 Jul    1 stop  28 hrs 25 min  212426
1778  HND      London   31 Oct – 6 Nov    1 stop  14 hrs 45 min  220500
189   HND      London        21–28 Oct  Non-stop  14 hrs 25 min  223460
874   HND      London        13–19 Jun  Non-stop  14 hrs 25 min  223460
464   NRT      London        10–18 Jun    1 stop  39 hrs 10 min  232240
661   HND      London        24–30 May    1 stop  14 hrs 25 min  233000
1709  GMP      London  28 Sept – 6 Oct    1 stop  35 hrs 40 min  244069
1093  HND      London          1–7 Jul  Non-stop  14 hrs 25 min  245960
1543  HND      London  26 Sept – 2 Oct  Non-stop  14 hrs 25 min  245960
90    SYD      London        17–26 Jun   2 stops  43 hrs 20 min  247138
1355  NRT      London        19–28 Aug    1 stop  39 hrs 10 min  263430
1817  NRT      London        21–29 Oct    1 stop  39 hrs 10 min  264740
783   SYD      London        23–29 May   2 stops  28 hrs 25 min  269986
1316  HND      London        22–28 Aug  Non-stop  14 hrs 25 min  280960
1476  GMP      London  25 Aug – 3 Sept    1 stop  35 hrs 40 min  281362
1252  GMP      London          1–9 Jul    1 stop  35 hrs 40 min  281362
1224  SYD      London          1–8 Jul   2 stops  52 hrs 25 min  294254

      dep  destination             date       via           time   price
74    CGK  Los Angeles        5–12 Sept    1 stop  25 hrs 40 min  128932
1664  CGK  Los Angeles         1–8 Sept    1 stop  19 hrs 40 min  129103
1432  CGK  Los Angeles  30 Aug – 5 Sept    1 stop   26 hrs 5 min  129736
769   CGK  Los Angeles        24–30 May   2 stops  19 hrs 40 min  133380
1209  CGK  Los Angeles        22–29 Jul   2 stops         19 hrs  133380
170   KUL  Los Angeles         2–8 Sept    1 stop  19 hrs 30 min  136348
1715  GMP  Los Angeles         1–9 Sept   2 stops   27 hrs 5 min  137025
987   CGK  Los Angeles         3–11 Jun   2 stops  22 hrs 50 min  140716
1298  KUL  Los Angeles        11–17 Jul    1 stop  18 hrs 55 min  142478
859   KUL  Los Angeles        20–29 May   2 stops  19 hrs 35 min  155474
390   SIN  Los Angeles          3–9 Oct    1 stop   19 hrs 5 min  162273
847   SIN  Los Angeles         9–16 May    1 stop  19 hrs 10 min  162591
1744  SIN  Los Angeles         2–9 Sept    1 stop   19 hrs 5 min  164090
1911  SYD  Los Angeles        24–30 Oct    1 stop  23 hrs 55 min  171434
1678  SYD  Los Angeles        5–11 Sept    1 stop  23 hrs 55 min  171434
6     HKG  Los Angeles        11–17 Oct    1 stop         19 hrs  174222
265   HKG  Los Angeles   26 Oct – 3 Nov    1 stop   19 hrs 5 min  184259
1390  HKG  Los Angeles  31 Aug – 6 Sept    1 stop  19 hrs 25 min  184259
1618  HKG  Los Angeles        1–10 Sept    1 stop         19 hrs  194185
1065  SIN  Los Angeles        16–25 Jun    1 stop  22 hrs 45 min  196313
1286  SIN  Los Angeles          1–9 Jul    1 stop  19 hrs 55 min  196313
1258  GMP  Los Angeles         8–15 Jul    1 stop  23 hrs 55 min  196356
1036  GMP  Los Angeles   23 Jun – 2 Jul   2 stops  23 hrs 35 min  197226
734   HKG  Los Angeles        23–30 May    1 stop   19 hrs 5 min  204189
999   SYD  Los Angeles        16–24 Jun    1 stop         24 hrs  205859
1222  SYD  Los Angeles        18–24 Jul    1 stop  24 hrs 20 min  224653
1776  HND  Los Angeles   31 Oct – 6 Nov  Non-stop         10 hrs  242370
224   NRT  Los Angeles        17–23 Oct  Non-stop   9 hrs 55 min  242430
947   HKG  Los Angeles        13–20 Jun    1 stop   19 hrs 5 min  242442
872   HND  Los Angeles   27 Jun – 3 Jul   2 stops  10 hrs 20 min  248180
1091  HND  Los Angeles          1–7 Jul    1 stop   16 hrs 5 min  248240
1128  NRT  Los Angeles         1–10 Jul    1 stop  10 hrs 15 min  250430
1167  HKG  Los Angeles   25 Jul – 2 Aug    1 stop  16 hrs 40 min  254800
659   HND  Los Angeles         9–15 May  Non-stop   10 hrs 5 min  258370
909   NRT  Los Angeles        20–26 Jun  Non-stop         10 hrs  258430

      dep    destination             date       via           time   price
1946  GMP  San Francisco        21–29 Oct   2 stops  24 hrs 50 min  132697
1211  CGK  San Francisco        21–27 Jul    1 stop   28 hrs 5 min  133067
771   CGK  San Francisco        23–29 May    1 stop  33 hrs 10 min  133067
123   GMP  San Francisco  29 Aug – 4 Sept    1 stop  25 hrs 15 min  136844
1745  SIN  San Francisco         1–9 Sept    1 stop  19 hrs 15 min  139769
174   KUL  San Francisco  26 Sept – 2 Oct    1 stop  18 hrs 15 min  141740
816   GMP  San Francisco   27 May – 3 Jun   2 stops  24 hrs 55 min  144563
1034  GMP  San Francisco        14–23 Jun   2 stops  24 hrs 55 min  145501
861   KUL  San Francisco        13–19 May    1 stop  18 hrs 10 min  155474
7     HKG  San Francisco        5–11 Sept    1 stop  16 hrs 45 min  155807
1854  HKG  San Francisco        10–16 Oct    1 stop  16 hrs 45 min  156011
92    SYD  San Francisco        22–28 Aug    1 stop   22 hrs 5 min  171028
988   CGK  San Francisco   29 Jun – 8 Jul    1 stop  18 hrs 25 min  172071
785   SYD  San Francisco   25 May – 3 Jun   2 stops  21 hrs 45 min  189174
735   HKG  San Francisco        20–28 May    1 stop  16 hrs 50 min  191282
1287  SIN  San Francisco        18–24 Jul    1 stop  19 hrs 20 min  198583
1066  SIN  San Francisco   30 Jun – 9 Jul    1 stop  28 hrs 20 min  207462
1226  SYD  San Francisco        22–28 Jul   2 stops   25 hrs 3 min  213584
1003  SYD  San Francisco        17–26 Jun   2 stops  21 hrs 45 min  214516
948   HKG  San Francisco        13–20 Jun    1 stop  16 hrs 50 min  217921
1097  HND  San Francisco         1–10 Jul    1 stop   9 hrs 45 min  237770
193   HND  San Francisco        17–23 Oct    1 stop   9 hrs 45 min  237770
1782  HND  San Francisco   31 Oct – 6 Nov    1 stop   9 hrs 35 min  237770
1547  HND  San Francisco         2–9 Sept    1 stop  14 hrs 55 min  238630
1816  NRT  San Francisco          3–9 Oct    1 stop   18 hrs 4 min  243300
1581  NRT  San Francisco         2–8 Sept  Non-stop   9 hrs 30 min  244430
1168  HKG  San Francisco        11–17 Jul    1 stop   16 hrs 5 min  244992
878   HND  San Francisco   27 Jun – 3 Jul    1 stop  14 hrs 55 min  246040
912   NRT  San Francisco   27 Jun – 4 Jul  Non-stop   9 hrs 30 min  255430
665   HND  San Francisco         9–15 May    1 stop   9 hrs 35 min  263370
699   NRT  San Francisco         9–16 May  Non-stop   9 hrs 20 min  266430

      dep destination             date      via           time   price
120   GMP    New York        18–24 Oct   1 stop  28 hrs 15 min  159416
72    CGK    New York  26 Sept – 2 Oct   1 stop  29 hrs 35 min  169791
1208  CGK    New York        14–22 Jul   1 stop  36 hrs 30 min  170017
768   CGK    New York   24 May – 2 Jun   1 stop  29 hrs 40 min  181265
1253  GMP    New York        11–18 Jul   1 stop  28 hrs 15 min  182230
172   KUL    New York        18–26 Oct  2 stops  24 hrs 55 min  188685
1761  KUL    New York  28 Sept – 4 Oct  2 stops  24 hrs 55 min  188936
158   SIN    New York          3–9 Oct   1 stop  23 hrs 50 min  191408
1078  KUL    New York   30 Jun – 7 Jul  2 stops  59 hrs 51 min  193817
860   KUL    New York   30 May – 5 Jun   1 stop  21 hrs 45 min  199669
97    SYD    New York        17–23 Oct   1 stop  40 hrs 10 min  211480
1687  SYD    New York       13–19 Sept   1 stop  37 hrs 20 min  211982
1289  SIN    New York        15–22 Jul   1 stop  23 hrs 50 min  224493
8     HKG    New York        20–28 Oct   1 stop  20 hrs 10 min  232603
1620  HKG    New York  23 Sept – 1 Oct   1 stop  32 hrs 25 min  243108
1031  GMP    New York   27 Jun – 5 Jul   1 stop  28 hrs 15 min  247210
790   SYD    New York   23 May – 1 Jun   1 stop   25 hrs 5 min  247461
1454  SYD    New York  29 Aug – 4 Sept  2 stops  31 hrs 19 min  248333
1585  NRT    New York       19–25 Sept   1 stop  12 hrs 35 min  248430
231   NRT    New York          1–7 Nov   1 stop  15 hrs 53 min  249300
1781  HND    New York   31 Oct – 6 Nov   1 stop  22 hrs 43 min  252240
1068  SIN    New York   27 Jun – 6 Jul   1 stop  22 hrs 45 min  256012
1231  SYD    New York        21–29 Jul   1 stop  28 hrs 15 min  257598
736   HKG    New York   27 May – 2 Jun   1 stop  37 hrs 20 min  263117
1319  HND    New York  30 Aug – 5 Sept   1 stop  17 hrs 18 min  266240
1096  HND    New York          1–9 Jul   1 stop  13 hrs 15 min  267870
1008  SYD    New York        16–25 Jun  2 stops   31 hrs 9 min  273676
877   HND    New York   28 Jun – 7 Jul   1 stop  16 hrs 16 min  273740
1135  NRT    New York          1–7 Jul   1 stop  12 hrs 45 min  278430
703   NRT    New York         9–16 May   1 stop  12 hrs 55 min  279430
664   HND    New York        24–30 May   1 stop  23 hrs 42 min  280240
1169  HKG    New York         4–11 Jul   1 stop  19 hrs 30 min  290267
916   NRT    New York        13–20 Jun   1 stop  12 hrs 45 min  296430

      dep destination             date      via           time   price
1673  CGK      Boston       16–22 Sept  2 stops  27 hrs 54 min  215007
83    CGK      Boston        10–16 Oct  2 stops  28 hrs 49 min  215035
319   CGK      Boston        11–17 Oct  2 stops  28 hrs 49 min  215320
181   KUL      Boston       19–25 Sept  2 stops  26 hrs 51 min  219358
1308  KUL      Boston         1–10 Jul  2 stops  28 hrs 34 min  219649
9     HKG      Boston   27 Oct – 4 Nov  2 stops  35 hrs 46 min  228371
1217  CGK      Boston        22–31 Jul  2 stops  27 hrs 44 min  239155
2002  KUL      Boston         3–12 Oct  2 stops  26 hrs 45 min  249554
1794  HND      Boston   31 Oct – 6 Nov   1 stop         20 hrs  251240
205   HND      Boston  27 Sept – 3 Oct   1 stop  19 hrs 14 min  251240
237   NRT      Boston       12–18 Sept   1 stop  20 hrs 49 min  251300
1364  NRT      Boston  26 Aug – 1 Sept   1 stop  19 hrs 54 min  251300
1332  HND      Boston  30 Aug – 5 Sept   1 stop   27 hrs 9 min  256240
1140  NRT      Boston          1–7 Jul   1 stop  19 hrs 44 min  261300
268   HKG      Boston        1–10 Sept  2 stops  35 hrs 50 min  262804
1109  HND      Boston          1–8 Jul   1 stop   19 hrs 4 min  266240
1463  SYD      Boston  29 Aug – 4 Sept  2 stops  31 hrs 40 min  266580
677   HND      Boston         9–15 May   1 stop  15 hrs 59 min  271240
890   HND      Boston        21–30 Jun   1 stop   19 hrs 5 min  271240
708   NRT      Boston         9–16 May   1 stop  20 hrs 53 min  271300
921   NRT      Boston        17–24 Jun   1 stop  19 hrs 49 min  271300
994   CGK      Boston   30 Jun – 9 Jul  2 stops  27 hrs 44 min  273072
141   GMP      Boston  31 Aug – 9 Sept  2 stops  27 hrs 26 min  273710
1731  GMP      Boston         1–8 Sept  2 stops  24 hrs 37 min  274073
1274  GMP      Boston          1–9 Jul  2 stops  24 hrs 27 min  284651
1393  HKG      Boston  30 Aug – 8 Sept  2 stops  35 hrs 50 min  286343
1239  SYD      Boston        15–24 Jul  2 stops  31 hrs 20 min  286854
834   GMP      Boston        16–23 May  2 stops  25 hrs 13 min  289680

      dep destination             date      via           time   price
150   GMP     Toronto  30 Sept – 7 Oct  2 stops  24 hrs 44 min  213566
1677  CGK     Toronto  23 Sept – 1 Oct  2 stops  29 hrs 11 min  219468
87    CGK     Toronto        20–27 Oct  2 stops  28 hrs 27 min  230315
1566  HND     Toronto  26 Sept – 2 Oct   1 stop  15 hrs 29 min  241260
1801  HND     Toronto   31 Oct – 6 Nov   1 stop   15 hrs 2 min  241260
212   HND     Toronto         4–10 Oct   1 stop  15 hrs 29 min  241260
1600  NRT     Toronto       12–18 Sept   1 stop  21 hrs 16 min  245560
246   NRT     Toronto        17–23 Oct   1 stop  21 hrs 16 min  245560
1221  CGK     Toronto        22–31 Jul  2 stops  28 hrs 16 min  247371
1116  HND     Toronto         4–11 Jul   1 stop  19 hrs 52 min  256500
185   KUL     Toronto        19–27 Oct  2 stops  24 hrs 46 min  256552
1444  CGK     Toronto  25 Aug – 1 Sept  2 stops  24 hrs 38 min  257768
1339  HND     Toronto  26 Aug – 1 Sept   1 stop  17 hrs 12 min  261500
684   HND     Toronto         9–15 May   1 stop         20 hrs  267500
897   HND     Toronto        21–27 Jun   1 stop  19 hrs 52 min  267500
716   NRT     Toronto        10–19 May   1 stop  21 hrs 25 min  267560
843   GMP     Toronto        16–23 May  2 stops  25 hrs 45 min  271779
998   CGK     Toronto        24–30 Jun  2 stops  27 hrs 50 min  283665
1507  GMP     Toronto  25 Aug – 3 Sept  2 stops   25 hrs 8 min  284967
929   NRT     Toronto         6–12 Jun   1 stop  21 hrs 30 min  290560
1282  GMP     Toronto          1–9 Jul  2 stops  24 hrs 41 min  292957
1061  GMP     Toronto   22 Jun – 1 Jul  2 stops   26 hrs 3 min  299094

      dep destination             date      via           time   price
777   CGK     Seattle   24 May – 2 Jun  2 stops         31 hrs  132037
144   GMP     Seattle        17–24 Oct  2 stops  22 hrs 45 min  132521
1734  GMP     Seattle  30 Sept – 7 Oct  2 stops  22 hrs 45 min  132697
84    CGK     Seattle        5–11 Sept   1 stop         31 hrs  132794
1218  CGK     Seattle        13–21 Jul   1 stop         31 hrs  132971
1441  CGK     Seattle        15–21 Aug  2 stops  22 hrs 19 min  134155
837   GMP     Seattle        20–28 May   1 stop  22 hrs 45 min  137025
1771  KUL     Seattle  27 Sept – 4 Oct  2 stops  39 hrs 10 min  141637
1501  GMP     Seattle        22–29 Aug  2 stops  23 hrs 44 min  147920
159   SIN     Seattle          3–9 Oct   1 stop  18 hrs 20 min  151385
867   KUL     Seattle        13–19 May  2 stops  39 hrs 10 min  155183
1055  GMP     Seattle   23 Jun – 1 Jul  2 stops  22 hrs 45 min  161515
1086  KUL     Seattle        22–28 Jun  2 stops  39 hrs 10 min  165755
995   CGK     Seattle         3–11 Jun  2 stops  22 hrs 16 min  167151
1536  KUL     Seattle        12–18 Aug  2 stops  29 hrs 57 min  170572
101   SYD     Seattle        17–23 Oct   1 stop  34 hrs 40 min  171028
1691  SYD     Seattle       14–21 Sept  2 stops   27 hrs 9 min  172306
1458  SYD     Seattle  25 Aug – 3 Sept  2 stops   27 hrs 9 min  178976
1234  SYD     Seattle        13–22 Jul   1 stop  34 hrs 30 min  179037
1012  SYD     Seattle   30 Jun – 9 Jul   1 stop  43 hrs 35 min  181520
852   SIN     Seattle   23 May – 1 Jun   1 stop  18 hrs 20 min  199741
1290  SIN     Seattle          1–9 Jul   1 stop  18 hrs 20 min  201672
11    HKG     Seattle         6–14 Oct  2 stops  14 hrs 40 min  204902
1395  HKG     Seattle  31 Aug – 9 Sept  2 stops  14 hrs 40 min  229691
1623  HKG     Seattle       23–30 Sept  2 stops  14 hrs 40 min  230672
739   HKG     Seattle        16–22 May   1 stop  19 hrs 55 min  232810
1551  HND     Seattle       19–25 Sept   1 stop  12 hrs 31 min  241170
1786  HND     Seattle   31 Oct – 6 Nov   1 stop  12 hrs 31 min  241770
1101  HND     Seattle         1–10 Jul   1 stop   9 hrs 10 min  242770
1825  NRT     Seattle        24–30 Oct   1 stop  14 hrs 24 min  243300
236   NRT     Seattle  26 Sept – 2 Oct   1 stop  14 hrs 19 min  243300
1363  NRT     Seattle  26 Aug – 1 Sept   1 stop  20 hrs 54 min  243300
1069  SIN     Seattle   24 Jun – 1 Jul   1 stop  31 hrs 15 min  243568
882   HND     Seattle   27 Jun – 3 Jul  2 stops  12 hrs 31 min  250580
1324  HND     Seattle  29 Aug – 4 Sept   1 stop   9 hrs 10 min  250770
669   HND     Seattle   31 May – 6 Jun   1 stop  12 hrs 32 min  257170
920   NRT     Seattle        20–26 Jun   1 stop  13 hrs 21 min  259300
707   NRT     Seattle         9–16 May   1 stop  14 hrs 18 min  259300
952   HKG     Seattle        20–27 Jun  2 stops  14 hrs 40 min  294229

      dep destination             date       via           time   price
118   GMP       Paris   26 Oct – 4 Nov    1 stop  28 hrs 30 min  170408
879   HND       Paris         6–12 Jun    1 stop  16 hrs 35 min  214400
666   HND       Paris   26 May – 4 Jun    1 stop  14 hrs 35 min  215480
194   HND       Paris   28 Oct – 6 Nov    1 stop  14 hrs 40 min  217980
1098  HND       Paris        15–24 Jul  Non-stop  14 hrs 35 min  218870
1475  GMP       Paris        19–28 Aug    1 stop  35 hrs 30 min  219229
574   SYD       Paris        20–27 Jun   2 stops  37 hrs 20 min  224015
1029  GMP       Paris        13–19 Jun   2 stops  20 hrs 45 min  226586
1548  HND       Paris  30 Sept – 9 Oct  Non-stop  14 hrs 35 min  228870
795   SYD       Paris        25–31 May   2 stops  28 hrs 15 min  229083
1708  GMP       Paris  26 Sept – 2 Oct    1 stop  35 hrs 30 min  233355
1251  GMP       Paris         8–17 Jul    1 stop  35 hrs 30 min  244656
811   GMP       Paris         9–15 May    1 stop  28 hrs 15 min  244656
102   SYD       Paris   27 Oct – 5 Nov   2 stops  28 hrs 40 min  254329
1321  HND       Paris        15–21 Aug    1 stop  14 hrs 35 min  262980
229   NRT       Paris   30 May – 8 Jun   2 stops         38 hrs  265360
1459  SYD       Paris  29 Aug – 4 Sept   2 stops  29 hrs 10 min  277203

      dep destination             date       via           time   price
238   NRT      Vienna         7–13 Jun  Non-stop  14 hrs 15 min  193630
139   GMP      Vienna        13–19 Jun    1 stop  29 hrs 30 min  203307
1962  GMP      Vienna         7–15 Oct    1 stop  29 hrs 30 min  204707
1827  NRT      Vienna   31 Oct – 6 Nov    1 stop  28 hrs 35 min  228760
709   NRT      Vienna   31 May – 6 Jun  Non-stop  14 hrs 15 min  231130
1592  NRT      Vienna  30 Sept – 6 Oct  Non-stop  14 hrs 15 min  241130
1729  GMP      Vienna  30 Sept – 7 Oct    1 stop  29 hrs 30 min  241334
832   GMP      Vienna   30 May – 6 Jun    1 stop  29 hrs 30 min  244724
201   HND      Vienna  26 Sept – 4 Oct    1 stop  18 hrs 55 min  249990
886   HND      Vienna        13–21 Jun    1 stop  16 hrs 45 min  252250
1790  HND      Vienna   28 Oct – 4 Nov    1 stop  17 hrs 20 min  257250
1018  SYD      Vienna        17–23 Jun    1 stop  38 hrs 35 min  260873
673   HND      Vienna        17–26 May    1 stop  17 hrs 25 min  264750
1105  HND      Vienna         4–11 Jul    1 stop  16 hrs 45 min  267250
180   KUL      Vienna         9–16 Jun    1 stop  41 hrs 10 min  282220
1328  HND      Vienna  29 Aug – 4 Sept    1 stop  18 hrs 55 min  284750
343   SYD      Vienna  31 Aug – 6 Sept   2 stops  26 hrs 30 min  299485
1930  SYD      Vienna        17–23 Oct   2 stops  26 hrs 30 min  299485
1697  SYD      Vienna         2–8 Sept   2 stops  26 hrs 30 min  299485

      dep destination             date      via           time   price
178   KUL   Las Vegas        5–11 Sept  2 stops  24 hrs 44 min  163501
1083  KUL   Las Vegas        16–24 Jun  2 stops  24 hrs 38 min  163718
854   SIN   Las Vegas         9–16 May  2 stops   23 hrs 4 min  165270
1986  SIN   Las Vegas         7–15 Oct  2 stops   27 hrs 5 min  165588
132   GMP   Las Vegas         2–9 Sept  2 stops  22 hrs 37 min  170092
163   SIN   Las Vegas        5–14 Sept  2 stops   23 hrs 2 min  171022
80    CGK   Las Vegas        22–28 Aug  2 stops  22 hrs 41 min  174095
1532  KUL   Las Vegas  30 Aug – 5 Sept  2 stops  24 hrs 44 min  174743
1214  CGK   Las Vegas        22–28 Jul  2 stops  31 hrs 18 min  175231
1306  KUL   Las Vegas        11–17 Jul  2 stops  22 hrs 28 min  175325
1519  SIN   Las Vegas  26 Aug – 3 Sept  2 stops  23 hrs 36 min  186139
774   CGK   Las Vegas        10–16 May  2 stops  26 hrs 40 min  190156
825   GMP   Las Vegas        23–29 May  2 stops  19 hrs 58 min  194197
95    SYD   Las Vegas       12–18 Sept  2 stops   29 hrs 9 min  200214
331   SYD   Las Vegas  31 Aug – 6 Sept  2 stops   29 hrs 9 min  200689
1229  SYD   Las Vegas        13–22 Jul  2 stops  28 hrs 50 min  206488
1918  SYD   Las Vegas   26 Oct – 4 Nov  2 stops   29 hrs 9 min  208292
1292  SIN   Las Vegas          1–8 Jul  2 stops  23 hrs 22 min  221678
14    HKG   Las Vegas        12–19 Oct  2 stops  24 hrs 14 min  222102
1626  HKG   Las Vegas        2–11 Sept  2 stops  24 hrs 14 min  226709
439   HND   Las Vegas         4–12 Nov   1 stop  12 hrs 58 min  241170
1557  HND   Las Vegas        2–10 Sept   1 stop  15 hrs 55 min  242640
203   HND   Las Vegas  29 Aug – 4 Sept   1 stop  15 hrs 55 min  242640
1792  HND   Las Vegas   31 Oct – 6 Nov   1 stop  16 hrs 21 min  243240
888   HND   Las Vegas   27 Jun – 3 Jul  2 stops  15 hrs 23 min  249050
1147  NRT   Las Vegas         1–10 Jul   1 stop  13 hrs 32 min  251300
1006  SYD   Las Vegas        14–23 Jun  2 stops   29 hrs 3 min  253909
1107  HND   Las Vegas          1–9 Jul   1 stop  12 hrs 52 min  256240
1043  GMP   Las Vegas   29 Jun – 8 Jul  2 stops  19 hrs 58 min  256353
715   NRT   Las Vegas         9–15 May   1 stop  13 hrs 20 min  259300
928   NRT   Las Vegas        20–26 Jun   1 stop  13 hrs 15 min  259300
1173  HKG   Las Vegas        18–24 Jul  2 stops   20 hrs 7 min  267825
741   HKG   Las Vegas   30 May – 7 Jun  2 stops  20 hrs 27 min  270042
788   SYD   Las Vegas   27 May – 5 Jun  2 stops   29 hrs 3 min  279251
675   HND   Las Vegas   30 May – 5 Jun   1 stop  13 hrs 12 min  280140
953   HKG   Las Vegas         3–12 Jun  2 stops   24 hrs 8 min  280655

      dep destination             date       via           time   price
128   GMP     Chicago        17–24 Oct    1 stop  26 hrs 45 min  159416
1901  CGK     Chicago          3–9 Oct    1 stop  29 hrs 45 min  175641
1435  CGK     Chicago  26 Aug – 1 Sept   2 stops  24 hrs 23 min  176512
176   KUL     Chicago       19–25 Sept    1 stop  31 hrs 25 min  177837
1997  KUL     Chicago        10–16 Oct    1 stop  31 hrs 25 min  178073
862   KUL     Chicago        10–19 May   2 stops         38 hrs  178364
1304  KUL     Chicago         1–10 Jul   2 stops  26 hrs 10 min  179237
1081  KUL     Chicago        16–24 Jun   2 stops  35 hrs 11 min  179528
1039  GMP     Chicago   30 Jun – 8 Jul    1 stop         39 hrs  186987
1212  CGK     Chicago          1–8 Jul   2 stops  26 hrs 15 min  189695
1530  KUL     Chicago        23–29 Aug   2 stops  25 hrs 13 min  190552
989   CGK     Chicago         2–11 Jun   2 stops  29 hrs 55 min  192749
15    HKG     Chicago        11–17 Oct    1 stop  37 hrs 25 min  194989
1627  HKG     Chicago         1–8 Sept   2 stops  27 hrs 48 min  196107
116   SYD     Chicago        17–23 Oct    1 stop  26 hrs 55 min  211480
38    HKG     Chicago         4–13 Nov    1 stop         31 hrs  216343
240   NRT     Chicago   31 Oct – 6 Nov  Non-stop  11 hrs 45 min  248430
1367  NRT     Chicago  30 Aug – 5 Sept  Non-stop  11 hrs 55 min  248430
821   GMP     Chicago        20–28 May    1 stop  21 hrs 15 min  248759
199   HND     Chicago  26 Sept – 2 Oct    1 stop         16 hrs  249240
1326  HND     Chicago  29 Aug – 4 Sept    1 stop         16 hrs  249240
1553  HND     Chicago         2–8 Sept    1 stop         12 hrs  253370
924   NRT     Chicago   28 Jun – 7 Jul  Non-stop  11 hrs 55 min  262930
1103  HND     Chicago          1–7 Jul    1 stop         16 hrs  268740
884   HND     Chicago   29 Jun – 7 Jul    1 stop  18 hrs 52 min  269240
711   NRT     Chicago         9–16 May    1 stop  11 hrs 55 min  277430
809   SYD     Chicago        23–30 May    1 stop  26 hrs 45 min  277873
1249  SYD     Chicago        18–24 Jul    1 stop  26 hrs 45 min  277873
671   HND     Chicago        10–16 May    1 stop         16 hrs  278240
1027  SYD     Chicago        13–20 Jun    1 stop         33 hrs  284482

      dep destination             date      via           time   price
680   HND        Rome        19–26 May   1 stop  20 hrs 55 min  224980
208   HND        Rome        13–21 Jun   1 stop  18 hrs 30 min  225090
1015  SYD        Rome        10–16 Jun  2 stops  34 hrs 35 min  226072
1562  HND        Rome  30 Sept – 7 Oct   1 stop  18 hrs 30 min  250090
1112  HND        Rome          1–9 Jul   1 stop  18 hrs 30 min  252590
122   GMP        Rome        13–20 Jun  2 stops  22 hrs 40 min  253970
104   SYD        Rome        16–23 May  2 stops  30 hrs 10 min  256210
1797  HND        Rome   28 Oct – 5 Nov  2 stops  20 hrs 45 min  256590
480   NRT        Rome   30 May – 6 Jun  2 stops  43 hrs 35 min  262680

      dep       destination             date      via           time   price
129   GMP  Washington, D.C.        17–23 Oct  2 stops  33 hrs 30 min  160285
1486  GMP  Washington, D.C.  29 Aug – 4 Sept  2 stops   33 hrs 3 min  171799
1719  GMP  Washington, D.C.         1–9 Sept   1 stop  39 hrs 55 min  175686
1262  GMP  Washington, D.C.          1–9 Jul   1 stop  39 hrs 55 min  175686
79    CGK  Washington, D.C.        9–18 Sept  2 stops  29 hrs 33 min  176278
1040  GMP  Washington, D.C.   23 Jun – 1 Jul   1 stop  39 hrs 55 min  186987
822   GMP  Washington, D.C.        23–30 May  2 stops  27 hrs 40 min  193531
177   KUL  Washington, D.C.        23–30 Jun   1 stop  32 hrs 20 min  225072
1766  KUL  Washington, D.C.         1–7 Sept   1 stop  37 hrs 35 min  229800
990   CGK  Washington, D.C.        20–27 Jun  2 stops  25 hrs 46 min  236041
1531  KUL  Washington, D.C.  23 Aug – 1 Sept   1 stop  37 hrs 35 min  236687
1213  CGK  Washington, D.C.        15–23 Jul   1 stop  29 hrs 25 min  238331
17    HKG  Washington, D.C.   28 Oct – 4 Nov  2 stops  38 hrs 47 min  239146
413   KUL  Washington, D.C.        23–29 May   1 stop  39 hrs 20 min  243088
207   HND  Washington, D.C.        25–31 Oct   1 stop  17 hrs 20 min  249240
248   NRT  Washington, D.C.        24–30 Oct   1 stop  17 hrs 35 min  249300
1561  HND  Washington, D.C.       19–25 Sept   1 stop  12 hrs 50 min  253370
1796  HND  Washington, D.C.   31 Oct – 6 Nov   1 stop  12 hrs 50 min  253370
1334  HND  Washington, D.C.  30 Aug – 5 Sept   1 stop  16 hrs 26 min  257240
1111  HND  Washington, D.C.         1–10 Jul   1 stop  21 hrs 41 min  262240
931   NRT  Washington, D.C.   28 Jun – 7 Jul   1 stop  37 hrs 28 min  263800
892   HND  Washington, D.C.   28 Jun – 6 Jul   1 stop  21 hrs 41 min  269240
743   HKG  Washington, D.C.   27 May – 3 Jun  2 stops  42 hrs 47 min  280655
1400  HKG  Washington, D.C.  25 Aug – 2 Sept  2 stops  35 hrs 26 min  280655
679   HND  Washington, D.C.        13–21 May   1 stop  16 hrs 46 min  283240
1150  NRT  Washington, D.C.          1–7 Jul   1 stop  37 hrs 35 min  286300

      dep destination             date     via           time   price
1558  HND    İstanbul        5–11 Sept  1 stop  21 hrs 25 min  244610
440   HND    İstanbul  30 Sept – 8 Oct  1 stop  21 hrs 25 min  246210
204   HND    İstanbul         4–12 Nov  1 stop  25 hrs 20 min  263710
1793  HND    İstanbul   31 Oct – 6 Nov  1 stop  25 hrs 20 min  271510
889   HND    İstanbul        14–23 Jun  1 stop  21 hrs 25 min  297710

    dep destination      date     via           time   price
19  HKG      Mumbai  2–8 Sept  1 stop  29 hrs 20 min  248530

      dep destination             date      via           time   price
179   KUL       Miami        13–19 May  2 stops  37 hrs 28 min  229366
137   GMP       Miami        14–22 Jul  2 stops  43 hrs 56 min  239524
1866  HKG       Miami         6–15 Oct  2 stops   37 hrs 7 min  239773
1307  KUL       Miami        22–28 Jul  2 stops  42 hrs 41 min  247873
1606  NRT       Miami         2–8 Sept   1 stop   34 hrs 8 min  249300
1841  NRT       Miami          3–9 Oct   1 stop   34 hrs 8 min  249300
252   NRT       Miami       12–18 Sept   1 stop   34 hrs 8 min  249300
20    HKG       Miami        5–11 Sept  2 stops   35 hrs 8 min  250901
1048  GMP       Miami   27 Jun – 5 Jul  2 stops  44 hrs 12 min  251143
217   HND       Miami         4–11 Nov   1 stop  17 hrs 46 min  252240
43    HKG       Miami       15–24 Sept  2 stops   35 hrs 8 min  254623
744   HKG       Miami        16–22 May  2 stops  42 hrs 13 min  255585
1806  HND       Miami   31 Oct – 6 Nov   1 stop         18 hrs  257240
1344  HND       Miami  29 Aug – 4 Sept   1 stop  16 hrs 28 min  259240
81    CGK       Miami        22–31 Jul  2 stops  25 hrs 38 min  260692
775   CGK       Miami   27 May – 3 Jun  2 stops  29 hrs 28 min  260726
992   CGK       Miami         3–12 Jun  2 stops  27 hrs 25 min  260726
1533  KUL       Miami         5–14 Aug  2 stops  25 hrs 33 min  261904
1438  CGK       Miami          2–9 Aug  2 stops  25 hrs 38 min  271609
1494  GMP       Miami        22–28 Aug  2 stops  32 hrs 58 min  277463
1401  HKG       Miami  29 Aug – 5 Sept  2 stops  40 hrs 23 min  281282
935   NRT       Miami        17–26 Jun  2 stops  34 hrs 25 min  286030
722   NRT       Miami        20–28 May  2 stops  36 hrs 13 min  286030
1177  HKG       Miami        18–24 Jul  2 stops  23 hrs 18 min  286265
1154  NRT       Miami        11–18 Jul  2 stops  35 hrs 11 min  293030

      dep destination             date      via           time   price
183   KUL   San Diego        10–19 May  2 stops  24 hrs 26 min  159336
1087  KUL   San Diego   24 Jun – 2 Jul  2 stops  31 hrs 37 min  159839
85    CGK   San Diego        15–21 Jul  2 stops  31 hrs 44 min  167932
165   SIN   San Diego        5–11 Sept  2 stops  23 hrs 44 min  176804
1754  SIN   San Diego        2–10 Sept  2 stops  23 hrs 44 min  177056
1537  KUL   San Diego         8–14 Aug  2 stops  22 hrs 40 min  177620
855   SIN   San Diego        23–29 May  2 stops  27 hrs 47 min  187070
145   GMP   San Diego        13–20 Jun  2 stops  32 hrs 12 min  192450
838   GMP   San Diego   27 May – 3 Jun  2 stops  32 hrs 12 min  201181
113   SYD   San Diego  29 Aug – 4 Sept  2 stops   29 hrs 9 min  207799
1521  SIN   San Diego        15–21 Aug  2 stops  23 hrs 35 min  210096
1703  SYD   San Diego         1–9 Sept  2 stops   29 hrs 9 min  218429
1442  CGK   San Diego         3–10 Aug  2 stops  22 hrs 45 min  218526
1294  SIN   San Diego   25 Jul – 3 Aug  2 stops  23 hrs 40 min  219520
1631  HKG   San Diego        8–14 Sept  2 stops  39 hrs 14 min  221805
996   CGK   San Diego        17–23 Jun  2 stops   26 hrs 4 min  227755
1277  GMP   San Diego          1–9 Jul  2 stops  32 hrs 14 min  228100
1072  SIN   San Diego   28 Jun – 4 Jul  2 stops  27 hrs 49 min  230556
1867  HKG   San Diego          3–9 Oct  2 stops  20 hrs 29 min  231063
1178  HKG   San Diego        14–23 Jul  2 stops  39 hrs 10 min  239460
21    HKG   San Diego  31 Aug – 9 Sept  2 stops  23 hrs 49 min  242516
1798  HND   San Diego   31 Oct – 6 Nov  2 stops   20 hrs 4 min  242640
1113  HND   San Diego         1–10 Jul   1 stop  16 hrs 35 min  243240
1563  HND   San Diego         2–8 Sept   1 stop  21 hrs 34 min  243240
1024  SYD   San Diego        13–22 Jun  2 stops   29 hrs 2 min  243772
745   HKG   San Diego        12–19 May  2 stops  23 hrs 56 min  248405
1502  GMP   San Diego        22–28 Aug  2 stops   20 hrs 4 min  250703
1246  SYD   San Diego        18–24 Jul  2 stops   29 hrs 4 min  253909
894   HND   San Diego   27 Jun – 3 Jul   1 stop  15 hrs 22 min  256240
681   HND   San Diego         9–15 May   1 stop  21 hrs 16 min  259240
925   NRT   San Diego        20–26 Jun   1 stop  22 hrs 52 min  259300
806   SYD   San Diego        17–26 May  2 stops  28 hrs 51 min  294457

      dep  destination             date      via           time   price
184   KUL  New Orleans         9–16 May  2 stops  28 hrs 40 min  229657
619   GMP  New Orleans        19–28 May  2 stops  29 hrs 20 min  233807
147   GMP  New Orleans        20–28 May  2 stops  29 hrs 15 min  236319
221   HND  New Orleans        5–11 Sept   1 stop  18 hrs 46 min  249240
257   NRT  New Orleans         2–8 Sept   1 stop   19 hrs 1 min  249300
1348  HND  New Orleans  29 Aug – 4 Sept   1 stop  16 hrs 45 min  254240
1810  HND  New Orleans          3–9 Oct   1 stop  16 hrs 50 min  254240
1632  HKG  New Orleans         1–7 Sept  2 stops  35 hrs 25 min  266726
1279  GMP  New Orleans          1–9 Jul  2 stops  28 hrs 33 min  279012
940   NRT  New Orleans   28 Jun – 7 Jul   1 stop  19 hrs 13 min  286300
1125  HND  New Orleans          1–7 Jul   1 stop  18 hrs 58 min  291240

      dep destination             date       via           time   price
1814  NRT   Hong Kong        11–17 Oct  Non-stop   4 hrs 50 min   95270
1352  NRT   Hong Kong        23–29 Aug  Non-stop   4 hrs 50 min   95270
697   NRT   Hong Kong        10–16 May  Non-stop          5 hrs   95270
1129  NRT   Hong Kong         5–11 Jul  Non-stop   4 hrs 50 min   95270
1092  HND   Hong Kong        18–24 Jul  Non-stop   4 hrs 40 min  101210
873   HND   Hong Kong   27 Jun – 3 Jul  Non-stop   4 hrs 40 min  101210
1777  HND   Hong Kong        17–23 Oct  Non-stop   4 hrs 40 min  101210
1315  HND   Hong Kong          1–7 Aug  Non-stop   4 hrs 40 min  101210
188   HND   Hong Kong         9–15 May  Non-stop   4 hrs 40 min  101210
1542  HND   Hong Kong        5–11 Sept  Non-stop   4 hrs 40 min  101210
1579  NRT   Hong Kong        6–12 Sept  Non-stop   4 hrs 50 min  121770
130   GMP   Hong Kong        18–24 Oct    1 stop   16 hrs 5 min  142577
1720  GMP   Hong Kong  26 Sept – 2 Oct    1 stop  17 hrs 35 min  144236
1263  GMP   Hong Kong        11–17 Jul    1 stop  17 hrs 35 min  144236
823   GMP   Hong Kong        23–29 May    1 stop  17 hrs 35 min  149897
166   KUL   Hong Kong   28 Jun – 4 Jul    1 stop  15 hrs 30 min  177837
1988  KUL   Hong Kong         7–16 Oct    1 stop  22 hrs 15 min  179204
402   KUL   Hong Kong         4–11 Jul    1 stop  39 hrs 30 min  180304
638   KUL   Hong Kong  23 Aug – 1 Sept    1 stop  22 hrs 15 min  180336
1755  KUL   Hong Kong  27 Sept – 6 Oct    1 stop  22 hrs 15 min  184894
1073  KUL   Hong Kong        23–29 Jun    1 stop  22 hrs 15 min  192492
856   KUL   Hong Kong        20–26 May    1 stop  22 hrs 15 min  199572
152   SIN   Hong Kong        22–28 Aug    1 stop  14 hrs 20 min  204310
1284  SIN   Hong Kong        21–30 Jul    1 stop  14 hrs 20 min  204601
624   SIN   Hong Kong         7–13 Oct    1 stop  14 hrs 20 min  204601
1742  SIN   Hong Kong  26 Sept – 5 Oct    1 stop  14 hrs 20 min  204601
306   CGK   Hong Kong          1–8 Aug    1 stop  24 hrs 20 min  213692
767   CGK   Hong Kong        20–28 May    1 stop  24 hrs 20 min  215217
70    CGK   Hong Kong         9–15 Aug    1 stop  15 hrs 35 min  215513
1893  CGK   Hong Kong        14–20 Oct    1 stop   14 hrs 5 min  216680
1206  CGK   Hong Kong   27 Jul – 2 Aug    1 stop   14 hrs 5 min  216680
782   SYD   Hong Kong   30 May – 5 Jun    1 stop  27 hrs 50 min  222453
89    SYD   Hong Kong  29 Aug – 4 Sept    1 stop  17 hrs 35 min  224981
1912  SYD   Hong Kong   31 Oct – 6 Nov    1 stop  18 hrs 10 min  225515
1000  SYD   Hong Kong         3–11 Jun    1 stop  17 hrs 35 min  225515
325   SYD   Hong Kong   25 Jul – 1 Aug    1 stop  17 hrs 35 min  225515
1679  SYD   Hong Kong         1–8 Sept    1 stop  17 hrs 35 min  225515
1509  SIN   Hong Kong         2–11 Aug    1 stop  14 hrs 20 min  280106

      dep destination             date      via           time   price
111   SYD      Prague        18–26 May  2 stops  34 hrs 20 min  225021
688   HND      Prague   27 May – 2 Jun   1 stop  20 hrs 35 min  234450
251   NRT      Prague        10–19 Jun  2 stops   43 hrs 5 min  236810
1570  HND      Prague  30 Sept – 8 Oct   1 stop  18 hrs 25 min  244450
1022  SYD      Prague        17–26 Jun  2 stops  34 hrs 20 min  246103
1840  NRT      Prague        10–18 Oct   1 stop  30 hrs 25 min  248830
1120  HND      Prague         1–10 Jul   1 stop  18 hrs 25 min  249450
135   GMP      Prague        13–19 Jun  2 stops  22 hrs 35 min  258541
1805  HND      Prague         4–13 Oct   1 stop  18 hrs 25 min  260830
828   GMP      Prague   27 May – 5 Jun  2 stops  22 hrs 35 min  261619
1605  NRT      Prague  23 Sept – 2 Oct   1 stop  30 hrs 25 min  274600
1343  HND      Prague  29 Aug – 4 Sept   1 stop  20 hrs 35 min  281950

      dep destination             date      via           time   price
202   HND   Amsterdam        14–20 Jun   1 stop  17 hrs 15 min  221500
1005  SYD   Amsterdam         3–11 Jun  2 stops  33 hrs 20 min  240619
674   HND   Amsterdam        16–22 May   1 stop  18 hrs 40 min  241500
235   NRT   Amsterdam         7–16 Oct  2 stops  28 hrs 55 min  241760
1791  HND   Amsterdam   31 Oct – 6 Nov   1 stop  19 hrs 35 min  256500
919   NRT   Amsterdam        13–21 Jun  2 stops  42 hrs 30 min  257460
1824  NRT   Amsterdam        21–29 Oct  2 stops  28 hrs 55 min  263840
706   NRT   Amsterdam   30 May – 8 Jun  2 stops  42 hrs 30 min  269960
820   GMP   Amsterdam   27 May – 4 Jun  2 stops  21 hrs 35 min  270332
1556  HND   Amsterdam  30 Sept – 8 Oct   1 stop  17 hrs 25 min  274000
1106  HND   Amsterdam         1–10 Jul   1 stop  17 hrs 25 min  279000
94    SYD   Amsterdam        18–26 May  2 stops  33 hrs 20 min  284142
127   GMP   Amsterdam        13–19 Jun  2 stops  21 hrs 35 min  288223
1329  HND   Amsterdam  29 Aug – 4 Sept   1 stop  19 hrs 35 min  289000
1451  SYD   Amsterdam  29 Aug – 6 Sept  2 stops  29 hrs 15 min  295339

      dep destination             date      via           time   price
907   HND      Dublin         7–16 Jun   1 stop  28 hrs 25 min  218220
222   HND      Dublin  30 Sept – 6 Oct   1 stop  18 hrs 25 min  252100
1811  HND      Dublin   31 Oct – 6 Nov  2 stops  21 hrs 55 min  252980
1126  HND      Dublin          1–9 Jul   1 stop  18 hrs 25 min  254600
96    SYD      Dublin        13–21 May  2 stops  34 hrs 20 min  266768
1007  SYD      Dublin         3–11 Jun  2 stops  44 hrs 20 min  272186

      dep destination            date      via           time   price
434   HND   Barcelona       24–30 Oct  2 stops  20 hrs 10 min  256800
198   HND   Barcelona  27 Jun – 4 Jul   1 stop         19 hrs  257800
239   NRT   Barcelona       15–22 Jun   1 stop  17 hrs 15 min  260400
1102  HND   Barcelona         1–9 Jul   1 stop  18 hrs 15 min  287800
126   GMP   Barcelona  28 Jun – 4 Jul  2 stops  22 hrs 25 min  290277
1552  HND   Barcelona        2–9 Sept   1 stop  20 hrs 25 min  290300

      dep destination            date      via           time   price
926   NRT      Madrid        6–12 Jun  2 stops  43 hrs 40 min  231680
206   HND      Madrid        4–13 Nov  2 stops  21 hrs 30 min  264110
1011  SYD      Madrid        3–11 Jun  2 stops  34 hrs 30 min  266539
1795  HND      Madrid  31 Oct – 6 Nov   1 stop  20 hrs 40 min  275460
1560  HND      Madrid      12–18 Sept   1 stop  20 hrs 45 min  295460

      dep destination             date      via           time   price
1839  NRT      Berlin         7–15 Oct   1 stop         28 hrs  226600
211   HND      Berlin        14–23 Jun   1 stop  29 hrs 15 min  249830
250   NRT      Berlin        15–22 Jun   1 stop         19 hrs  257320
1800  HND      Berlin   31 Oct – 6 Nov   1 stop  17 hrs 15 min  259720
1014  SYD      Berlin         3–10 Jun  2 stops         31 hrs  264634
683   HND      Berlin   27 May – 4 Jun   1 stop  17 hrs 15 min  267220
1604  NRT      Berlin  30 Sept – 6 Oct  2 stops  39 hrs 45 min  268860
1565  HND      Berlin       12–18 Sept   1 stop  17 hrs 15 min  277220
1115  HND      Berlin         1–10 Jul   1 stop  17 hrs 15 min  282220
103   SYD      Berlin        18–24 May  2 stops         31 hrs  291889
1338  HND      Berlin  29 Aug – 4 Sept   1 stop  18 hrs 15 min  292220
134   GMP      Berlin        17–26 Jun  2 stops  31 hrs 15 min  294453

      dep destination             date      via           time   price
900   HND      Lisbon        13–19 Jun   1 stop  20 hrs 25 min  219790
249   NRT      Lisbon         8–15 Jun  2 stops  43 hrs 20 min  251990
215   HND      Lisbon   28 Oct – 4 Nov   1 stop  20 hrs 20 min  257510
1804  HND      Lisbon   31 Oct – 6 Nov   1 stop  20 hrs 20 min  257510
1569  HND      Lisbon  30 Sept – 7 Oct   1 stop  20 hrs 10 min  279790
1119  HND      Lisbon          1–9 Jul   1 stop  20 hrs 10 min  294790

      dep destination             date     via           time   price
108   SYD   New Delhi  25 Aug – 1 Sept  1 stop  33 hrs 10 min  258000
1019  SYD   New Delhi        13–19 Jun  1 stop   24 hrs 5 min  264390
1931  SYD   New Delhi   26 Oct – 3 Nov  1 stop  25 hrs 10 min  269459
801   SYD   New Delhi        16–22 May  1 stop   24 hrs 5 min  270270
1241  SYD   New Delhi        25–31 Jul  1 stop   24 hrs 5 min  270270
1698  SYD   New Delhi         1–7 Sept  1 stop   24 hrs 5 min  270270

      dep destination             date      via           time   price
213   HND      Venice        13–19 Jun   1 stop  17 hrs 20 min  251040
1117  HND      Venice         1–10 Jul   1 stop  17 hrs 30 min  253960
1802  HND      Venice        14–21 Oct   1 stop  17 hrs 30 min  253960
109   SYD      Venice        16–22 May  2 stops  29 hrs 35 min  255198
1567  HND      Venice  30 Sept – 8 Oct   1 stop  17 hrs 30 min  263960
817   GMP      Venice        16–23 May  2 stops   22 hrs 5 min  264885
1020  SYD      Venice         3–10 Jun  2 stops  33 hrs 25 min  269256
124   GMP      Venice        17–23 Jun  2 stops  21 hrs 40 min  277581

      dep destination            date      via           time   price
692   HND    Budapest       19–28 May   1 stop   21 hrs 5 min  227810
905   HND    Budapest  24 Jun – 2 Jul   1 stop  18 hrs 55 min  255310
1809  HND    Budapest        7–15 Oct   1 stop   18 hrs 5 min  262810
1574  HND    Budapest       2–10 Sept   1 stop   21 hrs 5 min  281690
110   SYD    Budapest       18–24 May  2 stops  34 hrs 50 min  296267

      dep destination             date      via           time   price
899   HND  Copenhagen        14–21 Jun   1 stop  17 hrs 15 min  224770
1023  SYD  Copenhagen        10–16 Jun  2 stops  33 hrs 10 min  233888
151   GMP  Copenhagen        13–21 Jun  2 stops  33 hrs 10 min  236454
1568  HND  Copenhagen  30 Sept – 8 Oct   1 stop  17 hrs 25 min  244770
214   HND  Copenhagen        21–29 Oct   1 stop  19 hrs 35 min  247270
844   GMP  Copenhagen   27 May – 4 Jun  2 stops  21 hrs 35 min  258557
112   SYD  Copenhagen        18–26 May  2 stops  33 hrs 10 min  261347
1341  HND  Copenhagen  29 Aug – 4 Sept   1 stop  19 hrs 25 min  282270

      dep destination       date      via           time   price
1807  HND    Florence    3–9 Oct   1 stop  17 hrs 55 min  270920
138   GMP    Florence  17–23 Jun  2 stops  21 hrs 55 min  284172
831   GMP    Florence  16–23 May  2 stops  21 hrs 55 min  299613

     dep destination            date      via           time   price
219  HND      Athens  31 Oct – 6 Nov  2 stops  21 hrs 45 min  294560

      dep destination             date      via           time   price
385   GMP   Melbourne  30 Sept – 8 Oct  2 stops  40 hrs 40 min  169075
149   GMP   Melbourne  29 Aug – 7 Sept  2 stops  23 hrs 55 min  172000
210   HND   Melbourne        16–23 Jun   1 stop  13 hrs 50 min  174507
1114  HND   Melbourne          1–7 Jul   1 stop  13 hrs 50 min  178220
1564  HND   Melbourne         1–7 Sept   1 stop  13 hrs 50 min  178220
1337  HND   Melbourne          1–7 Aug   1 stop  13 hrs 50 min  183220
682   HND   Melbourne   30 May – 5 Jun   1 stop  13 hrs 50 min  188220
1799  HND   Melbourne          3–9 Oct   1 stop  13 hrs 50 min  193220
842   GMP   Melbourne        12–18 May  2 stops  20 hrs 50 min  263823
1060  GMP   Melbourne         6–15 Jun  2 stops  20 hrs 50 min  291454

Empty DataFrame
Columns: [dep, destination, date, via, time, price]
Index: []

      dep destination            date       via          time   price
195   HND       Seoul       13–19 Jun  Non-stop  2 hrs 15 min   52310
667   HND       Seoul        9–16 May  Non-stop  2 hrs 15 min   52310
1099  HND       Seoul         1–9 Jul  Non-stop  2 hrs 15 min   52310
1322  HND       Seoul       22–28 Aug  Non-stop  2 hrs 15 min   52310
1549  HND       Seoul        1–7 Sept  Non-stop  2 hrs 15 min   52310
1784  HND       Seoul  31 Oct – 6 Nov  Non-stop  2 hrs 30 min   52310
234   NRT       Seoul        9–15 May  Non-stop  2 hrs 30 min  189370
918   NRT       Seoul        6–12 Jun  Non-stop  2 hrs 30 min  189370
1137  NRT       Seoul        4–10 Jul  Non-stop  2 hrs 30 min  189370
1361  NRT       Seoul         1–7 Aug  Non-stop  2 hrs 30 min  189370
1588  NRT       Seoul      12–18 Sept  Non-stop  2 hrs 30 min  189370
1823  NRT       Seoul         3–9 Oct  Non-stop  2 hrs 30 min  189370

Empty DataFrame
Columns: [dep, destination, date, via, time, price]
Index: []